services:
  portfolio:
    build: .
    image: emilianofinetti/emilianofinettisite:latest 
    container_name: emiliano-finetti
    ports:
      - "8080:80"
    restart: unless-stopped
    # (Opzionale) Mappiamo solo la configurazione di Nginx, se vuoi poterla modificare a caldo
    volumes:
      - ./conf:/etc/nginx/conf.d:ro