server {
    listen 80;
    server_name emilianofinetti.com;
    return 301 $scheme://www.emilianofinetti.com$request_uri;
}

server {
    listen 80 default_server;
    server_name www.emilianofinetti.com localhost "";
    
    root /usr/share/nginx/html;
    index index.html index.htm;
    
    error_page 404 /404.html;

    location / {
        absolute_redirect off; 
        try_files $uri $uri/ =404;
    }

    location = /404.html {
        internal;
    }
}